### ISSUE TITLE
Lack of documentation

### ISSUE THREAD

**Issue by kirit93** [Riamse/ceterach#1]
Could you please document this code in a better way? It would be great if you could write a test case to show exactly how we can use ceterach to extract information off a Wikipedia page.

Thanks!

**Comment by Riamse** [comment]
Oops, I just noticed this.
Yeah, I'm working on that.

**Comment by irl** [comment]
Ping. Any updates on documentation appearing?

**Comment by Riamse** [comment]
@kirit93  @irl I wrote a thing.

**Comment by irl** [comment]
Awesome thanks.

**Comment by irl** [comment]
If you could provide some Sphinx docs on the full API, that would be awesome. I'm considering if this is useful enough to me that I'd like to put it into Debian.

**Comment by Riamse** [comment]
Hm, it is in theory possible to generate Sphinx docs from the docstrings. Would you like me to generate the html files and actually put them on github for all to see?

**Comment by irl** [comment]
That would be cool (:

**Comment by Riamse** [comment]
@irl Cool, cool.

Hey, I know development's stalled a bit on this; Looking back, I'm having trouble deciding on an actually stable API (e.g. the MediaWiki query continue changes prompted me to just make the MediaWiki.old_iterator and a MediaWiki.new_iterator methods), with the goal of not being a Wikimedia-website-only framework and also being able to work on Wikimedia websites.

**Comment by Riamse** [comment]
I don't know why I'm telling you this; I think it's a big-picture question as to what direction ceterach should take.

**Comment by irl** [comment]
My use case is for a non-Wikimedia site, so supporting Mediawiki's API and not Wikimedia-specific APIs would be what I'm after, if that helps. Sorry I've not looked at this for a while, it's coming around again in my todo list though.

**Comment by Riamse** [comment]
> Sorry I've not looked at this for a while, it's coming around again in my todo list though.

me_irl
